# Generated by Django 3.2.5 on 2021-07-07 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='insigator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='consultations.userprofile', verbose_name='инициатор'),
        ),
        migrations.AlterField(
            model_name='application',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='consultations.topic', verbose_name='Категория'),
        ),
    ]
