# Generated by Django 3.2.5 on 2021-07-07 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_auto_20210707_0525'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkerProfile',
        ),
        migrations.RemoveField(
            model_name='application',
            name='topic',
        ),
        migrations.AddField(
            model_name='conclusion',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма оценки'),
        ),
        migrations.AlterField(
            model_name='conclusion',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='consultations.application'),
        ),
        migrations.AlterField(
            model_name='conclusion',
            name='final',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
