# Generated by Django 3.2.5 on 2021-07-07 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_auto_20210707_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conclusion',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='consultations.application'),
        ),
    ]
