# Generated by Django 3.2.5 on 2021-07-19 14:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_alter_conclusion_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_code', models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=255, null=True)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cons_text', models.TextField(blank=True, default='', verbose_name='Заключение консультанта')),
                ('user_text', models.TextField(blank=True, default='', verbose_name='Комментарий товароведа')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма оценки')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='Данные о предмете')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('final', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'В очереди'), (1, 'В работе'), (3, 'Завершена')], default=0)),
                ('consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultations.userprofile')),
                ('insigator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='insigator', to='consultations.userprofile', verbose_name='инициатор')),
            ],
            options={
                'verbose_name': 'Заключение',
                'verbose_name_plural': 'Заключения',
            },
        ),
        migrations.RemoveField(
            model_name='conclusion',
            name='application',
        ),
        migrations.RemoveField(
            model_name='conclusion',
            name='consultant',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='auth_code',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='consultations.authcode'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='conclusion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='consultations.consultation'),
        ),
        migrations.DeleteModel(
            name='Conclusion',
        ),
    ]
